server:
  port: 9000
spring:
  application:
    name: scw-order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.80.166:3306/atcrowdfunding
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.80.166
    port: 6379
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  