spring:
  application:
    name: cloud-consumer-user-feign-hystrix-actuator
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  #在注册中心保存id
feign:
  hystrix:
    enabled: true   #默认false,开启feign声明 
       
management:
  endpoints:
    web:
      exposure:
        include: '*' # 访问/actuator/hystrix.stream能看到不断更新的监控流